{% set name = "libdiffpy" %}
{% set version = "1.4.0" %}
{% set sha256 = "d89351286881b18abcc413a2e27e94cc89124dedf69c9a095b9052179f8878c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 7
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('libdiffpy', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - scons
  host:
    - libboost-devel
    - gsl
    - libobjcryst
  run:
    # NOTE libobjcryst is implicitly added by libobjcryst run_exports
    - gsl

test:
  commands:
    - test -f $PREFIX/lib/libdiffpy${SHLIB_EXT}

about:
  home: https://github.com/diffpy/libdiffpy
  summary: C++ calculators of PDF, bond valence sum and other pair quantities.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://www.diffpy.org/libdiffpy/
  dev_url: https://github.com/diffpy/libdiffpy

extra:
  recipe-maintainers:
    - pavoljuhas
    - sbillinge
    - st3107
